#!/bin/sh
#
### BEGIN ININT INFO
# Provides: splashscreen
# Required-Start: weston
# Required-Stop: weston
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
### END INIT INFO

if test -e /etc/default/splashscreen ; then
    . /etc/default/splashscreen
fi

killproc() {
    pid=`/bin/pidof $1`
    [ "$pid" != "" ] && kill $pid
}

read CMDLINE > /proc/cmdline
for x in $CMDLINE; do
    case $x in
    splashscreen=false)
            echo "App disabled"
            exit 0;
            ;;
    esac
done

case "$1" in 
    start)
        . /etc/profile
                
        export HOME=/home/root
        export XDG_RUNTIME_DIR=/run/user/1000
        export WAYLAND_DISPLAY=wayland-1
                
        # Start App
        splashscreen
    ;;

    stop)
        echo "Stopping App"
        
        killproc splashscreen
    ;;

    restart)
        $0 stop
        sleep 1
        $0 start
    ;;
    
    *)
        echo "usage: $0 { start | stop | restart }"
    ;;
esac

exit 0